[versions]
spotless = "6.25.0"
sonarqube = "5.0.0.4638"

[libraries]

[plugins]
spotless = { id = "com.diffplug.spotless",version.ref="spotless"}
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }

[bundles]
